language: bash
services: docker
env:
  - VERSION=maxscale

install:
  - git clone https://github.com/mariadb-corporation/mariadb-docker-images ~/mariadb-docker-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="maxscale-docker:$VERSION"

script:
  - travis_retry docker build -t "$image" .
  - ~/mariadb-docker-images/test/run.sh "$image"

after_script:
- docker images

notifications:
  email:
    recipients:
      - cpe@mariadb.com
    on_success: never # default: change
    on_failure: always # default: always